export const SET_ARTICLES_COUNT = 'SET_ARTICLES_COUNT';
export const SET_ARTICLES_LIST = 'SET_ARTICLES_LIST';
export const SET_ARTICLES_LIST_PAGE = 'SET_ARTICLE_LIST_PAGE';
export const SET_ARTICLES_OFFSET = 'SET_ARTICLE_OFFSET';
export const SET_CURRENT_ARTICLE = 'SET_CURRENT_ARTICLE';

export const SET_FORM_ERROR = 'SET_FORM_ERROR';
export const SET_LOADING_CONDITION = 'SET_LOADING_CONDITION';

export const USER_REGISTRATION = 'USER_REGISTRATION';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const USER_LOGIN = 'USER_LOGIN';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
